### ISSUE TITLE
内容简介与作者简介似乎有点问题。

### ISSUE THREAD

**Issue by iiwenwen** [Captain2021/MyTranslator#1]
详细见图

<img width="332" alt="Snipaste_2021-09-26_19-22-33" src="https://user-images.githubusercontent.com/25455839/134805608-030c7c4f-dec9-4b1f-92b1-64fd78970412.png">

**Comment by TanGuangZhi** [comment]
具体什么问题？还是想要如下图效果（换行）？
PS：下图效果可下载最新douban.js。
![image](https://user-images.githubusercontent.com/53848822/134874630-160b5dd4-5dc9-4268-8738-7b806db3836b.png)

**Comment by TanGuangZhi** [comment]
已修复
![Uploading image.png…]()

**Comment by iiwenwen** [comment]
@TanGuangZhi 感谢。
