### ISSUE TITLE
豆瓣条目出现BGU

### ISSUE THREAD

**Issue by iiwenwen** [Captain2021/MyTranslator#2]
出版社一栏出现HTML和副标题，短标题显示为空。

![image](https://user-images.githubusercontent.com/25455839/160143966-4310404f-d636-46ff-81ec-6480b3848238.png)

Zotero版本6.0.3
谷歌浏览器版本 97.0.4692.71（正式版本） (x86_64)

**Comment by TanGuangZhi** [comment]
应该是选择器的问题，下一版修复

**Comment by TanGuangZhi** [comment]
@iiwenwen 该bug已在最新版DouBanSimple.js 中解决
